---
title: "HW6"
output: html_document
name: Montgomery Inman
---
Link: https://github.com/montgomeryinman/HW6
Group: Montgomery Inman

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
data(happy, package="productplots")
head(happy)

happy <- readRDS("data/HAPPY.rds")
```

#1)
```{r}
happy = replace(happy, happy == "IAP", NA)
happy = replace(happy, happy == "DK", NA)
happy = replace(happy, happy == "NA", NA)
```

#2)
```{r}
happy$AGE <- as.numeric(happy$AGE)

cols = c("HAPPY", "SEX","MARITAL", "DEGREE", "FINRELA", "HEALTH", "PARTYID", "POLVIEWS")

happy[cols] <- lapply(happy[cols], factor) 

happy$AGE[happy$AGE == "89 or older"] = 89
str(happy)
```

```{r}

library(tidyverse)
HAPPY <- happy %>% mutate(
  happy = factor(tolower(HAPPY))
) %>% select(-HAPPY)

levels(HAPPY$happy)
```
```{r}
HAPPY <- replace(HAPPY, HAPPY == "IAP", NA)
HAPPY <- replace(HAPPY, HAPPY == "DK", NA)
HAPPY <- replace(HAPPY, HAPPY == "NA", NA)
```

```{r}
HAPPY <- HAPPY %>% mutate(
  age = replace(AGE, AGE == "89 AND OLDER", 89),
  age = as.numeric(age)
) %>% select(-AGE)

HAPPY %>% ggplot(aes(x = age)) + geom_histogram(binwidth=1)
```
```{r}
## REORDER DEGREE...

HAPPY <- HAPPY %>% mutate(
  degree = factor(tolower(DEGREE)),
  degree = factor(degree, levels=c("lt high school", "high school", "junior college", "bachelor", "graduate school"))
) %>% select(-DEGREE)

HAPPY %>% ggplot(aes(x = degree)) + geom_bar()
```
```{r}
# REORDER MARITAL
HAPPY <- HAPPY %>% mutate(
  marital = factor(tolower(MARITAL)),
  marital = factor(marital, levels=c("never married", "married", "divorced", "seperated", "widowed"))
) %>% select(-MARITAL)
```

```{r}
# REORDER FINRELA
HAPPY <- HAPPY %>% mutate(
  finrela = factor(tolower(FINRELA)),
  finrela = factor(finrela, levels=c("far below average", "below average", "average", "above average", "far above average"))
) %>% select(-FINRELA)
```

```{r}
# REORDER HEALTH
HAPPY <- HAPPY %>% mutate(
  health = factor(tolower(HEALTH)),
  health = factor(health, levels=c("poor", "fair", "good", "excellent"))
) %>% select(-HEALTH)
```

```{r}
# REORDER PARTYID
HAPPY <- HAPPY %>% mutate(
  partyid = factor(tolower(PARTYID)),
  partyid = factor(partyid, levels=c("strong democrat", "not str democrat", "ind, near dem", "independent", "ind, near rep","not str republican", "strong republican", "other party"))
) %>% select(-PARTYID)
```


```{r}
#Making graph
happyMaritalDegree = 
  HAPPY %>% group_by(degree, SEX) %>% 
  summarise(m.happy = mean(as.numeric(happy), na.rm = TRUE), 
            size = n()) %>% 
  
arrange(m.happy)


happyMaritalDegree%>% 
  ggplot(aes(x = degree, fill = SEX)) + 
  geom_bar(aes(weight = m.happy), position = position_dodge()) + 
  labs(title = "Happiness on degree and gender", y = "Happiness")
```


This graph compares degree with happiness level, seperated by male and female. We can see 
that females are generally more happier than men, except for the lt high school. We can also
observe that people with bachelor degrees are happier than any other degree, not including NA.



